### ISSUE TITLE
Docker build fails with the below error

### ISSUE THREAD

**Issue by ZeeshanLive** [launchdarkly/hello-nginx#6]
TMP_DIR=$(mktemp -d -t ci-XXXXXXXXXX)
mktemp -d -t ci-XXXXXXXXXX
cd $TMP_DIR

git clone https://github.com/launchdarkly/c-server-sdk.git
Cloning into 'c-server-sdk'...
cd c-server-sdk
mkdir build && cd build

cmake -D BUILD_TESTING=OFF -D BUILD_SHARED_LIBS=ON ..
CMake Error at CMakeLists.txt:1 (cmake_minimum_required):
  CMake 3.10 or higher is required.  You are running version 3.5.1

**Comment by cwaldren-ld** [comment]
@ZeeshanLive thanks for the report, I'll take a look at this.

_Filed internally as 150666_.

**Comment by cwaldren-ld** [comment]
Hi @ZeeshanLive , please  `git pull` and try again.

**Comment by cwaldren-ld** [comment]
Hi @ZeeshanLive , I will close the issue now. Please feel free to file another issue if you have any more problems.
